server:
  port: 8081

spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    jdbc-url: jdbc:log4jdbc:mysql://avnadmin:[password]@[url]
    username: avnadmin
    password: password
    hikari:
      maximum-pool-size: 20
  config:
    activate:
      on-profile: local
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: GOOGLE_CLIENT
            client-secret: GOOGLE_SECRET
            scope: # google API의 범위 값
              - profile
              - email

mybatis:
  config-location: classpath:/mybatis-config.xml
  mapper-locations: classpath:/mappers/**/*.xml
  type-aliases-package: com.admin.the_climbing_night

logging:
  file:
    path: "logs"
    name: "spring-boot-turorial"

key:
  section: # 구간 암복호화
    aes-key: 654321zyxwvutsrqponmlkjihgfedcba
  database: # database 암복호화
    aes-key: abcdefghijklmnopqrstuvwxyz123456

jwt:
  access-token-exp-time: 86400000 # 1일
  refresh-token-exp-time: 2592000000 # 30일
  secret-key: 6dbd7e7d120c47b0446038cba0b5149c1b48d722536d164937f3ec07f22d46f6
